insert into Drivers values (1,'Test1','Testowy2',20,10);
insert into Drivers values (2,'Test2','Testowy3',22,20);
insert into Drivers values (3,'Test3','Testowy3',30,13);


CREATE TABLE DRIVERS (
DRIVER_ID NUMBER(5) PRIMARY KEY,
FIRSTNAME VARCHAR(15) NOT NULL,
LASTNAME VARCHAR(15) NOT NULL,
AGE NUMBER(2) NOT NULL,
AVG_FUEL_CONSUMPTION NUMBER(5));

CREATE TABLE TASKS (
TASK_ID NUMBER(5) PRIMARY KEY,
START_DATE DATE,
END_DATE DATE,
DRIVER_ID NUMBER(5)
CONSTRAINT DRIVER_FKEY REFERENCES DRIVERS
                     (DRIVER_ID),
PRODUCER_ID NUMBER(5)
CONSTRAINT PRODUCER_FKEY REFERENCES PRODUCERS
                     (PRODUCER_ID));

CREATE TABLE PRODUCERS(
PRODUCER_ID NUMBER(5) PRIMARY KEY,
PRODUCER_NAME VARCHAR(15) NOT NULL,
DISTANCE NUMBER(5));